### ISSUE TITLE
Decide if we want to bump the version numbers of projects that do not follow the BrainVISA versioning:

### ISSUE THREAD

**Issue by ylep** [brainvisa/brainvisa.github.io#120]
- [x] Bump version of development/casa-distro/master to 3.2.0?
- [x] Bump version of soma/soma-workflow/master to 3.3.0?
- [x] Bump version of capsul/master to 2.4.0?
- [x] Bump version of populse/populse_db/master to 2.3.0?

**Comment by denisri** [comment]
For me, yes to all.

**Comment by ylep** [comment]
Done
