### ISSUE TITLE
Add code quality checks to core projects

### ISSUE THREAD

**Issue by ylep** [brainvisa/brainvisa.github.io#17]
Add flake8 checks, Travis tests, possibly protect `master` branches.

- [x] [casa-distro](https://github.com/brainvisa/casa-distro)
- [x] [brainvisa-cmake](https://github.com/brainvisa/brainvisa-cmake)
- [x] [soma-base](https://github.com/populse/soma-base)
- [x] [soma-workflow](https://github.com/populse/soma-workflow)
- [x] [capsul](https://github.com/neurospin/capsul)
- [ ] [axon](https://github.com/brainvisa/axon)
- [ ] [aims-free](https://github.com/brainvisa/aims-free)
- [ ] [aims-gpl](https://github.com/brainvisa/aims-gpl)
- [ ] [anatomist-free](https://github.com/brainvisa/anatomist-free)
- [ ] [anatomist-gpl](https://github.com/brainvisa/anatomist-gpl)
- [ ] [morphologist](https://bioproj.extra.cea.fr/redmine/projects/brainvisa-t1mri)
- [ ] [morphologist-ui](https://github.com/brainvisa/morphologist)
- [ ] [morpho-deepsulci](https://github.com/brainvisa/morpho-deepsulci)

**Comment by sapetnioc** [comment]
I think we should close this issue. We can make a corresponding issue in each project when there is a chance that tests are added.
