### ISSUE TITLE
Make BrainVISA 5.0 release

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/brainvisa.github.io#20]
This issue will be the final one of the BrainVISA 5 release project. When casa_distro 3.0 is ready and tests are running, the work on this issue will start : perform version changes then create and publish BrainVISA 5.0 release.

- [x] Create v5.0.0 tags
- [x] Create brainvisa-5.0.0.simg
- [x] Create brainvisa-5.0.0.ova / vdi

**Comment by denisri** [comment]
I don't remember if we need to rebuild vbox images ?

**Comment by sapetnioc** [comment]
I thought no because last modifications were about Singularity display problem via x2go. But now I wonder if a change has been done on Constellation files permissions. If yes, this change is probably not included in VirtualBox.

**Comment by denisri** [comment]
Oh yes you're right we have added a rebuild of Constellation internal database. But as vbox images are not read-only this is maybe not critical (the user just has to click "OK" in the update databases dialog the first time he/she rune brainvisa). And this is only for the internal CEA distro.
