### ISSUE TITLE
BrainVISA 5.0 user use cases

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/brainvisa.github.io#23]
This issue is connected to #20 .
Its goal is to define precisely the minimum set of features that we expect to be functional in BrainVISA 5.0.  We should list here the various user environments we choose to support. For instance a single user with a single computer, an installation shared by several users on a read-only directory, etc.

**Comment by ylep** [comment]
Summary of today's visio call:

- Support Singularity and VirtualBox (leave Docker aside)
- Support Linux installation by an admin on a network (e.g. /neurospin/local) -> read-only for end users
- Support installation on a Linux cluster (e.g. alambic)
- Support one-machine Linux installation by a end user who has root access
- Support one-machine Windows installation by a end user who has admin access
  - With decent OpenGL performance
- Support one-machine Mac installation by a end user who has root access
- The release is not modular
- The user must be able to work with their data
- Support external software (SPM, FSL, MATLAB, FreeSurfer...) and document how to configure them for all environments


- If possible: support Windows installation by an admin on a network (e.g. in MIRCen) [probably not possible with VirtualBox]
