### ISSUE TITLE
BrainVISA 5.0 administrator use cases

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/brainvisa.github.io#24]
This issue is related to #20 
We must define how the BrainVISA team will work to make daily compilation, daily tests, virtual images updates, new releases, etc.

**Comment by ylep** [comment]
Summary of today's visio call:

- Use casa-distro 3 to release BrainVISA 5.0
  - Create images
  - Push them to `brainvisa.info/vbox` / `brainvisa.info/singularity`

- Release = image that includes all projects
  - New command `casa_distro_admin create_release` -> runs `make install-runtime` in an environment, copies the *install* directory into a `casa-run` image
  - Release for VirtualBox: should we use the *install* directory that is compiled in Singularity (and be sure that the release are exactly the same, and binary compatible), or compile everything under VirtualBox (and thus be 100% sure that the *install* directory is compatible with the VirtualBox system, which is slightly different from the Singularity system)?
  - A release is done on the `release_candidate` branches of individual projects. That branch evolves independently from `master`, only the release team has the right to commit to it. Thus, special build-workflows on the `release_candidate` branches are used when a release is being prepared.
  - The final release is tested manually (for the GUI)

- Tests : get tests to run nightly and get them to succeed in all supported environments
  - Run nightly tests on the `brainvisa` (public) and `cea` distros using the Singularity workflow
  - Create a release image and run tests in that image
  - Nightly tests run on the `master` branch

- Versioning / branch switches

- Web site: built with `bv_maker` in a `web` build-workflow (all of the public `brainvisa` build-workflow + the `web` project) (who does it, on which machine, at what frequency?)

**Comment by sapetnioc** [comment]
I think this issue is obsolete now
