### ISSUE TITLE
Merge (and delete?) the 'trunk' branch of Bioproj SVN projects

### ISSUE THREAD

**Issue by ylep** [brainvisa/brainvisa.github.io#26]
For each repository, we have to
1. Merge `trunk` into `bug_fix`
2. Maybe delete the `trunk` branch? I know that deleting branches on SVN has the effect of hiding them in a way, should we do this?

- [x] documentation
- [x] bibliography
- [x] web
- [x] soma-io-gpl
- [x] brainvisa_spm
- [x] datamind
- [x] morphologist-private
- [x] morphologist-gpl
- [x] baby
- [x] tms
- [x] sulci-data
- [x] sulci-private
- [x] sulci-models
- [x] constellation-gpl
- [x] constellation-private
- [x] cortical_surface-private
- [x] cortical_surface-gpl
- [x] freesurfer_plugin
- [x] data_storage_client
- [x] nuclear_imaging-gpl
- [x] nuclear_imaging-private
- [ ] pyptk
- [ ] fiber-clustering
- [x] snapbase
- [x] longitudinal_pipelines
- [ ] rsfmri

**Comment by denisri** [comment]
I can't guarantee all merges will be OK, some of them are extremely painful in codes I don't master. Some projects have been deeply modified (apply of python-modernize, manual modifs, etc) on both sides without merging...

**Comment by denisri** [comment]
pyptk, fiber-clustering and rsfmri don't have a bug_fix branch. And anyway they seem to be dead projects, so I leave them as is.

**Comment by denisri** [comment]
I leave the trunk branches for now, I don't really know if we can safely delete trunk branches from svn.
