### ISSUE TITLE
New tests handling infrastructure

### ISSUE THREAD

**Issue by denisri** [brainvisa/brainvisa.github.io#3]
We need a tool to run tests in an incremental way:
* validate a projects test when tests pass, for a single architecture.
* validate a projects tests globally when they pass on all target architectures.
* don't re-run tests when they have already have been validated, when no new commit has been made on the project, and when no upstream project has changed.

**Comment by Hboni** [comment]
I know [Travis CI](https://travis-ci.com/) to run test each time a commit/pull request is made.
I don't know exactly if/how we can set architecture in Travis.

[Circle CI](https://circleci.com/product/) is another tool to run test, I never configure it but already saw some repository using it.

**Comment by denisri** [comment]
Yes, we're using travis-ci in individual projects (small ones, in python, like capsul, soma-base, soma-workflow etc), but here it is more an inter-project dependency that we need to track: for instance re-run morphologist tests when aims has changed etc. Moreover strict "continuous integration" (running tests at each commit) is probably not the solution here because we push lots of commits in different projects, and each would involve lots of compilation and hours of testing, so it's more realistic to run them only once a day: typically every night, as we already do, but the way it is done should be improved.

**Comment by sapetnioc** [comment]
I think our new release system made this obsolete
