### ISSUE TITLE
Search is broken on brainvisa.info

### ISSUE THREAD

**Issue by ylep** [brainvisa/brainvisa.github.io#32]
The search leads to a 404 error on google.com

**Comment by denisri** [comment]
google has probably changed its search api... well, we need to look at it.

**Comment by denisri** [comment]
Yes it has visibly changed. It seems that we cannot any longer send a request on google/cse, but we need to create something (a "personalized search engine") on google servers before. I'm not sure to understand what it is before doing it...

**Comment by denisri** [comment]
Well, I'll do it anyway...

**Comment by sapetnioc** [comment]
We may use another search engine such as DuckDockGo. For instance, searching for `constellation` in brainvisa.info site with `!brainvisa.info constellation` give the following URL : https://duckduckgo.com/?q=!brainvisa.info+constellation&t=h_&ia=web

**Comment by denisri** [comment]
OK let's go for duckduck, because I can't integrate the new google widget in our page layout and style (I can't avoid a line break and cannot force styles on every element).

**Comment by sapetnioc** [comment]
You are right, I did not share the procedure. I wrote a script for that : `web-build/src/communication/web/bug_fix/scripts/bv_publish_web`

**Comment by sapetnioc** [comment]
This scrip remove the directories it replaces. This is why we should not do any manual changes in `brainvisa.info` directory, it may be restored by a script.
