### ISSUE TITLE
reorganize dev docs on  brainvisa.github.io

### ISSUE THREAD

**Issue by denisri** [brainvisa/brainvisa.github.io#78]
The index page should present the main projects and development docs, and replace the old https://brainvisa.info/web/infrastructure.html#integrate

**Comment by denisri** [comment]
A first version of structure and links table has been done. There is more to be done but you can have a look.

**Comment by sapetnioc** [comment]
I close this issue since the global job is done. More specific issues can be added.

**Comment by denisri** [comment]
No it's not really done, but never mind. We have no time to do things well...
